apiVersion: v1
kind: Service
metadata:
  name: register-app-service
spec:
  selector:
    app: register-app
  ports:
    - protocol: TCP
      port: 80        # The port the world sees
      targetPort: 8080 # The port your Java app runs on
  type: LoadBalancer   # Creates an AWS Load Balancer for you
